### ISSUE TITLE
cPanel plugin not working

### ISSUE THREAD

**Issue by MohamedMohsenX2** [vivex/cPanel4j#14]
cPanel Version: WHM 60.0 (build 26)
OS: CloudLinux 7

The issue happening when I open the plugin from cPanel

> Child failed to make LIVEAPI connection to cPanel.

cPanel error log:

> PHP Parse error:  syntax error, unexpected '$this' (T_VARIABLE) in /cPanel4jCore/Tomcat.php on line 28
> [2016-12-08 15:25:22 +0200] die [Internal Death while parsing [live php] 10590] Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cpanel4j/page.live.php. at cpanel.pl line 4953.
>  at cpanel.pl line 4953.
> 	cpanel::cpanel::setup_external_engine() called at cpanel.pl line 800
> 	cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/cpanel4j/page.live.php") called at cpanel.pl line 306
> 
> 
> Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cpanel4j/page.live.php. at cpanel.pl line 4953.
> [2016-12-08 15:25:23 +0200] warn [cpsrvd] The subprocess (cpanel (cpanel)) exited with an error: The subprocess reported error number 10 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 156, <GEN15> line 14.
> 	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2aa3d50)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 71
> 	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2aa3d50), "subprocess_name", "cpanel (cpanel)", "subprocess_read_handle", IO::Handle=GLOB(0x2aa32b8), "subprocess_write_handle", IO::Handle=GLOB(0x2aa38b8), "api_type", "html", ...) called at cpsrvd.pl line 6433
> 	cpanel::cpsrvd::cpHandler("app", "cpanel", "document", "./frontend/paper_lantern/cpanel4j/page.live.php") called at cpsrvd.pl line 2340
> 	cpanel::cpsrvd::dodoc_cpaneld() called at cpsrvd.pl line 1584
> 	cpanel::cpsrvd::dodoc(HASH(0x139dcc0)) called at cpsrvd.pl line 1344
> 	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 836
> 	cpanel::cpsrvd::script() called at cpsrvd.pl line 319

Thanks

**Comment by MohamedMohsenX2** [comment]
Solved, The line 27 in file Tomcat.php need semicolon at the end of line __construct

**Comment by vivekfyi** [comment]
@MohamedMohsenX2  thanks for PR i merged that.
