### ISSUE TITLE
Not connect to Port

### ISSUE THREAD

**Issue by tiagoceridorio** [vivex/cPanel4j#16]
When install the plugin and create a instance I not have success on open http://mywebsite.com:port this link does work.

**Comment by vivekfyi** [comment]
Hi, @tiagoceridorio , Sorry but i couldn't get you.

You mean to say you are able to access tomcat at http://example.com:tomcatPort but not on http:/example.com ?

**Comment by tiagoceridorio** [comment]
Hi, @vivex I have acess to http://example.com but not to http://example.com:tomcatPort.

**Comment by vivekfyi** [comment]
Yup tomcat will serve on port 80 only (http://example.com)  to get  http://example.com:tomcatPort you need to enable this port in iptables.

**Comment by tiagoceridorio** [comment]
Hi @vivex , I have a ModSecurity™ Tools enabled in my server and there was blocked the redirect from tomcat, removing it solves the problem.
