### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by gccarvalhobr** [vivex/cPanel4j#5]
Hello guys, i´m using your plugin into a Client´s server, and my client called me today saing that his application gets an error, but on the test server this error not happens, and how i know nothing about tomcat or java i open this ticket.

The error message is:

Error 500:
Could not initialize class com.sun.org.apache.xerces.internal.impl.xs.SchemaGrammar

What could be? Thanks a lot

**Comment by vivekfyi** [comment]
how many apps they are running on that error ? can you paste all the files from `/cPanel4jCore/service-files` directory here

**Comment by gccarvalhobr** [comment]
Hello, aparently only this apps, above the files.

teccomex-tec.comexdez.com.br-tomcat-7.0.59.sh
`#!/bin/bash
#description: Tomcat-tec.comexdez.com.br start stop restart
#processname: tomcat-teccomex-tec.comexdez.com.br

#chkconfig: 234 20 80
 CATALINA_HOME=/cPanel4jCore/tomcat-7.0.59-engine
 export CATALINA_BASE=/home/teccomex/tec.comexdez.com.br/tomcat-7.0.59/

case $1 in
 start)
 sh $CATALINA_HOME/bin/startup.sh
 ;;
 stop)
 sh $CATALINA_HOME/bin/shutdown.sh
 ;;

restart)
 sh $CATALINA_HOME/bin/shutdown.sh
 sh $CATALINA_HOME/binstartup.sh
;;
 esac
 exit 0
`

There is also a index.php but this file is empty

**Comment by vivekfyi** [comment]
okkk and /home/teccomex/tec.comexdez.com.br/tomcat-7.0.59/conf/server.xml file please.

**Comment by gccarvalhobr** [comment]
Ok, the content of this file is:

`<?xml version = "1.0" encoding = "utf-8"?>
<Server port="11659" shutdown="SHUTDOWN">
    <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
    <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
                    <Listener className="org.apache.catalina.core.JasperListener" />
    <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
    <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
    <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />
    <GlobalNamingResources>
        <Resource name="UserDatabase" auth="Container"
                  type="org.apache.catalina.UserDatabase"
                  description="User database that can be updated and saved"
                  factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
                  pathname="conf/tomcat-users.xml" />
    </GlobalNamingResources>
    <Service name="Catalina">
        <Connector port="17577" protocol="HTTP/1.1"
                   connectionTimeout="20000"
                   redirectPort="8443" />
        <Connector port="7086" enableLookups="false"  protocol="AJP/1.3" redirectPort="8443" />
        <Engine name="Catalina" defaultHost="localhost">
            <Realm className="org.apache.catalina.realm.LockOutRealm">
                <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
                       resourceName="UserDatabase"/>
            </Realm>
            <Host name="localhost"  appBase="webapps"
                  unpackWARs="true" autoDeploy="true">
                <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
                       prefix="localhost_access_log." suffix=".txt"
                       pattern="%h %l %u %t &quot;%r&quot; %s %b" />
            </Host>
        </Engine>
    </Service>
</Server>
`

**Comment by gccarvalhobr** [comment]
Any news about the issue?? My client is calling me about the problem. Thanks

**Comment by vivekfyi** [comment]
Fixed.
