### ISSUE TITLE
cPanel 11.58  (build 8) fresh install 

### ISSUE THREAD

**Issue by ivspassov** [vivex/cPanel4j#7]
View Tomcat Instances- cPanel4J

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /cPanel4jCore/DBWrapper.php on line 26

Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /usr/local/cpanel/base/frontend/paper_lantern/cpanel4j/page.live.php on line 35

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /usr/local/cpanel/base/frontend/paper_lantern/cpanel4j/page.live.php on line 37

**Comment by edgardoalvarez100** [comment]
Fix...
