### ISSUE TITLE
Issue while creating tomcat instance

### ISSUE THREAD

**Issue by ESDSCOIN** [vivex/cPanel4j#9]
Hello,  

We are receiving the following error warning, while activating Tomcat instance for the domain from cPanel. 
# 

Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /usr/local/cpanel/base/frontend/paper_lantern/cpanel4j/page.live.php on line 35
# Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /usr/local/cpanel/base/frontend/paper_lantern/cpanel4j/page.live.php on line 37

Please let us know if any additional setting needs to be done on the server  to correct this issue.

**Comment by vivekfyi** [comment]
@ESDSCOIN  sorry for late response, you solved this ?
